name: Label Detector Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t label_detector --build-arg aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }} --target production . --file Dockerfile --tag my-image-name:$(date +%s)
